# Generated by Django 3.0.8 on 2020-07-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctionapp', '0002_auto_20200728_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessReport',
            fields=[
                ('successreport_id', models.AutoField(primary_key=True, serialize=False)),
                ('auctiondetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.AuctionDetails')),
                ('currentbid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctionapp.CurrentBid')),
            ],
        ),
        migrations.CreateModel(
            name='CancelReport',
            fields=[
                ('cancelreport_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancelreport_date', models.DateTimeField()),
                ('cancelreport_reason', models.TextField()),
                ('auctiondetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.AuctionDetails')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionQuery',
            fields=[
                ('auctionquery_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_query', models.TextField()),
                ('successreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportsapp.SuccessReport')),
            ],
        ),
    ]
