# Generated by Django 3.0.8 on 2020-07-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('productcategory_name', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('productimages_id', models.AutoField(primary_key=True, serialize=False)),
                ('productimages_image', models.FileField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('productsubcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('productsubcategory_name', models.CharField(max_length=36)),
                ('productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('productinformation_id', models.AutoField(primary_key=True, serialize=False)),
                ('productinformation_name', models.CharField(max_length=36)),
                ('productinformation_details', models.TextField()),
                ('product_verify', models.BooleanField(default=False)),
                ('productinformation_baseprice', models.FloatField()),
                ('productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.ProductCategory')),
                ('productsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.ProductSubcategory')),
            ],
        ),
    ]
