# Generated by Django 3.0.8 on 2020-07-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionDetails',
            fields=[
                ('auctiondetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('auctiondetails_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('autobid_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_price', models.FloatField()),
                ('increment_price_by', models.FloatField()),
                ('ending_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('bidder_id', models.AutoField(primary_key=True, serialize=False)),
                ('bidder_type', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAuction',
            fields=[
                ('currentauction_id', models.AutoField(primary_key=True, serialize=False)),
                ('auctiondetails', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auctionapp.AuctionDetails')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentBid',
            fields=[
                ('currentbid_id', models.AutoField(primary_key=True, serialize=False)),
                ('currentbid_time', models.TimeField()),
                ('currentbid_amount', models.FloatField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.Bidder')),
                ('currentauction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.CurrentAuction')),
            ],
        ),
    ]
