# Generated by Django 3.0.8 on 2020-07-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0001_initial'),
        ('userapp', '0001_initial'),
        ('auctionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.User'),
        ),
        migrations.AddField(
            model_name='autobid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.Bidder'),
        ),
        migrations.AddField(
            model_name='auctiondetails',
            name='productinformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.ProductInformation'),
        ),
    ]
